##mysql만 docker로 돌림
version: '3'
services:
  database:
    image: mysql:8
    container_name: db_container_gdsc2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: entertainment

#version: "3"
#services:
#  database:
#    image: mysql
#    environment:
#      MYSQL_DATABASE: entertain
##      MYSQL_USER: user2
##      MYSQL_PASSWORD: userpwd
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - 3306:3306
#    restart: always
#    networks:
#      - test
#  application:
#    build: .
#    ports:
#      - 8080:8080
#    depends_on:
#      - database
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/entertain
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#    networks:
#      - test
#    restart: always
#networks:
#  test: